# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Build binaries (amd64 and arm64)
      run: |
        GOOS=linux GOARCH=amd64 go build -o agent-linux-amd64 ./cmd/agent
        GOOS=linux GOARCH=arm64 go build -o agent-linux-arm64 ./cmd/agent
        GOOS=darwin GOARCH=arm64 go build -o agent-macos-arm64 ./cmd/agent

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          agent-linux-amd64
          agent-linux-arm64
          agent-macos-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
